/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   lib/utils/async.html
 */

/// <reference path="boot.d.ts" />

declare namespace Polymer {

  namespace Async {

    namespace timeOut {


      /**
       * Returns a sub-module with the async interface providing the provided
       * delay.
       */
      function after(delay: number): any|null;


      /**
       * Enqueues a function called in the next task.
       */
      function run(fn: Function|null): number;


      /**
       * Cancels a previously enqueued `timeOut` callback.
       */
      function cancel(handle: number): any;


      /**
       * Cancels a previously enqueued `animationFrame` callback.
       */
      function cancel(handle: number): any;
    }

    namespace animationFrame {


      /**
       * Enqueues a function called at `requestAnimationFrame` timing.
       */
      function run(fn: Function|null): number;
    }

    namespace idlePeriod {


      /**
       * Enqueues a function called at `requestIdleCallback` timing.
       */
      function run(fn: (p0: any|null) => any): number;


      /**
       * Cancels a previously enqueued `idlePeriod` callback.
       */
      function cancel(handle: number): any;
    }

    namespace microTask {


      /**
       * Enqueues a function called at microtask timing.
       */
      function run(callback: Function|null): number;


      /**
       * Cancels a previously enqueued `microTask` callback.
       */
      function cancel(handle: number): any;
    }
  }
}
